# Generated by Django 4.0.4 on 2022-06-01 03:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticapelicula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='edad_actor',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='actor',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='edad_director',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='director',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='año_de_realizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='resumen',
            field=models.TextField(default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='actor',
            name='biografia_actor',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='director',
            name='biografia_director',
            field=models.TextField(max_length=1000),
        ),
    ]
