# Generated by Django 4.0.4 on 2022-06-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticapelicula', '0003_alter_actor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='critica',
            name='estado',
            field=models.CharField(choices=[('e', 'En Espera'), ('a', 'Aceptado'), ('r', 'Rechazado')], default='e', max_length=1),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='foto_pelicula',
            field=models.ImageField(blank=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='foto_actor',
            field=models.ImageField(blank=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='director',
            name='foto_director',
            field=models.ImageField(blank=True, upload_to='upload/'),
        ),
    ]
