# Generated by Django 4.0.4 on 2022-06-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticapelicula', '0008_alter_actor_foto_actor_alter_director_foto_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='foto_actor',
            field=models.ImageField(blank=True, upload_to='actores/'),
        ),
        migrations.AlterField(
            model_name='director',
            name='foto_director',
            field=models.ImageField(blank=True, upload_to='directores/'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='foto_pelicula',
            field=models.ImageField(blank=True, upload_to='peliculas/'),
        ),
    ]
