# Generated by Django 4.0.4 on 2022-06-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticapelicula', '0010_alter_actor_fecha_de_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='año_de_realizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
