# Generated by Django 4.0.4 on 2022-07-31 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criticapelicula', '0011_alter_actor_fecha_de_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='critica',
            options={'permissions': (('puede_revisar_criticas', 'Revisa Criticas'),)},
        ),
    ]
