# Generated by Django 4.0.4 on 2022-06-01 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criticapelicula', '0002_actor_edad_actor_actor_fecha_de_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name_plural': 'Actores'},
        ),
    ]
