# Generated by Django 4.0.4 on 2022-06-07 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticapelicula', '0004_critica_estado_pelicula_foto_pelicula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='puntaje_pelicula',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='critica',
            name='puntaje_critica',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
