# Generated by Django 4.0.4 on 2022-06-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticapelicula', '0005_pelicula_puntaje_pelicula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='foto_actor',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='director',
            name='foto_director',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='foto_pelicula',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
